### ISSUE TITLE
Unable to view diff of modified files in 'Status' view

### ISSUE THREAD

**Issue by bharath144** [timbrel/GitSavvy#989]
I have a bunch of UNSTAGED changes in my Git repo. When I try to diff the file, nothing happens. The console prints the following Traceback.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "C:\Users\mgbh\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/interfaces/status.py", line 314, in run
AttributeError: 'NoneType' object has no attribute 'get_view_regions'
```
- Sublime Text version number
Version 3.1.1, Build 3176
- Git version number
git version 2.18.0.windows.1
- OS type and version
Windows 10
- Console error output
(See above)
- A description of the problem.
- Steps to reproduce, if possible
In git: status view, try to view diff of a file
- If the bug is caused by a failing command, [include a debug log](docs/debug.md#providing-a-debug-log).

**Comment by randy3k** [comment]
Were you using the dashboard or the command palette and which specific command were you using?

**Comment by randy3k** [comment]
The [e] key works perfectly fine for me. I have no idea what is causing it. Try to make sure you have the latest GitSavvy and completely restart Sublime Text.

**Comment by bharath144** [comment]
All of those done, same issue...

**Comment by randy3k** [comment]
How about the [l] key (inline diff)?

**Comment by linusr** [comment]
Doesn't work as well. [l], [e], [r], [i] doesn't work on Sublime 3.1.1 B3176 on Window.

Will try to test other keys as well.

**Comment by randy3k** [comment]
Same error?

**Comment by linusr** [comment]
Error is different in my case..

```
Traceback (most recent call last):
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\core/commands/inline_diff.py", line 38, in <lambda>
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\core/commands/inline_diff.py", line 63, in run_async
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\core/commands/inline_diff.py", line 100, in augment_color_scheme
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\common/theme_generator.py", line 133, in __init__
  File "./python3.3/json/__init__.py", line 329, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 22 column 5 (char 572)

Traceback (most recent call last):
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\core/commands/inline_diff.py", line 170, in run
  File "C:\Users\xyz\Apps\Sublime Text Build 3176 x64\Data\Installed Packages\GitSavvy.sublime-package\common/util/file.py", line 56, in get_file_contents_binary
  File "./python3.3/ntpath.py", line 113, in join
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by kaste** [comment]
The 'keys' don't do their work if the dashboard is in its render process. (#1033 does this different.)

Remember that we call `clear_regions()` basically immediately when a `render` is requested. Then we gather new data (partly in `before_render` or while resolving the template (inline)) which is or at least can be slow. Only after that we actually _draw_ and mark the regions again. 

So, TLDR; there is always a good chance that your actions don't do anything. 

(
Note: if you just open the status dashboard, it will block, t.i. not show a view at all, until the first render has finished. But if you switch views, you trigger a refresh, and the users sees everything as in place but it is not working. Just like amazon mobile, they draw the button but you just can't push it for another 10 seconds :-)
)

**Comment by kaste** [comment]
Closing due to age. It is probably fixed, otherwise the underlying code was rewritten (and will be rewritten again 😁).
